### ISSUE TITLE
Camera open error API level 25

### ISSUE THREAD

**Issue by mapiko** [memfis19/Annca#1]
Trying to open camera on Nexus 5X (Android 7.1.1 API 25)

 E/Camera2Controller: onCameraOpenError

**Comment by memfis19** [comment]
Hi, thank you for your feedback, I will take a look asap. And can you please clarify how do you use camera? Do you try to launch sample app or try to use within your app or..?

**Comment by mapiko** [comment]
Hey,

Trying to open camera on my own app.
There is no problem with camera1.

**Comment by memfis19** [comment]
Thank you for your feedback. Issue is fixed. Source code is available already. Will be available shortly in 0.3.1 version via jCenter. As I mentioned in description there can be some issues connected to the sizes of preview/photo/video.
