### ISSUE TITLE
Camera Preview Aspect-Ration problem

### ISSUE THREAD

**Issue by RHoumaidy** [memfis19/Annca#25]
Dear All

i faced a problem when using the CameraFagment Library on Samsung Tab 9",
the problem is when preview the camera before take photo or record video the aspect ratio is fine, but the preview not full the screen,
but when record video, while recording the aspect-ratio is stretched, but the saved video is fine

Best,

**Comment by memfis19** [comment]
Hi,
1. About recording the aspect-ratio is stretched: I know about this kind of behaviour and I have such even on some stock camera applications, nevertheless I have such task in a backlog, but fixing it on 1 device can break it on another. So I am not sure will it be fixed or not.
2. About preview not full the screen: it is also connected to the different supported camera sizes and how preview size is calculated. Current approach based on simplifying camera using, that why such entity as **media quality** was introduced - which calculating based on available camera sizes. And in some cases aspect ratio can be not as you expect, but for sure it is the best ratio for specific quality and preview sizes.

In future I want to make works or at least add enough ways to customize it. But for now I can only suggest to make fork and fix responsible methods for your functionality. In case of some questions you can write me directly via mail.
