### ISSUE TITLE
Camera Full Screen Problem on some devices

### ISSUE THREAD

**Issue by acemimhnds** [memfis19/Annca#26]
Hi,
Thanks for this library!
I am using your library and  most of devices that i have tried  camera is full screen but on Samsung Galaxy Note5 camera is square screen. I want to use camera full screen all devices. How can i do this?

It would be nice to hear from you.
Merve

**Comment by memfis19** [comment]
Hi please look at: https://github.com/memfis19/Annca/issues/25, https://github.com/memfis19/Annca/issues/5
