### ISSUE TITLE
Directly start video recorder 

### ISSUE THREAD

**Issue by hardikJoshi123** [memfis19/Annca#27]
Hello, 

 its a great library to record videos. I want to start video recorder directly when user click on buttton, I want to open full screen view which will record video, user can stop video by pressing stop button. Can you suggest if i can do it with this library ?

**Comment by memfis19** [comment]
Hi, do you want to press start button on your own activity?

**Comment by hardikJoshi123** [comment]
No. 

new Annca(videoLimited.build()).launchCamera();

 This will open a new activity having setting, camera flip and record button. I want to start recording directly when this activity will open. Also, i want to hide settings and flip buttons. User can only stop video recording. 

So, is there a way which i can pass parameter which will start recording directly when "Annca" activity open ?

**Comment by memfis19** [comment]
Hi, this is impossible with out of box solution, bit it is possible with customizing approach: you can check example how to customize and then i.e. just pass some additional parameter within bundle which will tells activity to start recording immediately.

**Comment by Anu07** [comment]
Hi

@hardikJoshi123 Were you able to get it working?
