### ISSUE TITLE
Camera Preview Orientation issue

### ISSUE THREAD

**Issue by muqeemht** [memfis19/Annca#28]
When I start recording, camera preview orientation is changed into the landscape .  how to fix to have it portrait mode, the  issue is occurring on Mi 4 device while its working fine on Samsung j5

**Comment by memfis19** [comment]
Hi, you should use Annca only in **portrait** mode. You should set all Annca activities in portrait mode in manifest file. You can go through README to find out how to do it. And possibly your device was in landscape and camera screen was rotated to the portrait mode.

**Comment by muqeemht** [comment]
Thank you for the response, working....
