### ISSUE TITLE
Nexus 7 - open front camera

### ISSUE THREAD

**Issue by mapiko** [memfis19/Annca#3]
Hello.

Is it possible to open front camera if back camera is not available?

Currently there is error:

 I/CameraManagerGlobal: getCameraService: Reconnecting to camera service
12-20 07:59:05.316 18385-22627/mobilepic.cvs_mobile.com.mobilepic D/Camera1Manager: Can't open camera: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

thank you

**Comment by memfis19** [comment]
Hi, should be possible, it doesn't matter how many cameras device has. Can you please describe what and how are you trying to do in details?
