### ISSUE TITLE
Front Camera layout to set to full screen

### ISSUE THREAD

**Issue by Ankurjain30** [memfis19/Annca#38]
Hi, presently front camera layout is not full screen, how to change this, it is showing a small picture. should be back camera layout.

**Comment by memfis19** [comment]
Hi. Everything is connected to the **camera** supported sizes and specifically **device display** size(**they are different**): in current solution I'm trying to adjust aspect ratio to show correct width and height and display camera/preview in full size. To achieve your wish I need to change the camera/preview adjusting behavior - to scale current camera/preview to match screen size. In such case the camera/preview will be cutted off. Maybe I'll add some configuration to choose behavior, but it seems to me that display full camera/preview is more correct behavior then cut off part of it.
