### ISSUE TITLE
Camera screen size

### ISSUE THREAD

**Issue by shiv71** [memfis19/Annca#5]
Hello sir when i select auto , 1920*1080 or 720*480 in setting then camera screen not cover full size and when i select 1280*720 camera screen cover full screen so i want full screen in auto size how it possible.

**Comment by memfis19** [comment]
Hi, yes I know, and its not an issue. Camera has limited predefined list of supported preview sizes, photo sizes, video sizes and when you select some specific size, library searches for the best one which match most to the current selected size aspect ratio and current screen size and it can be not full screen. Keep aspect ratio has higher priority then match screen size. In future I will add possibility to use custom algorithm for sizes calculation.
