### ISSUE TITLE
Get uri from captured photo (onActivityResult)

### ISSUE THREAD

**Issue by marcus-costa** [memfis19/Annca#52]
I made the following configuration:

AnncaConfiguration.Builder builder = new AnncaConfiguration.Builder(activity, CAPTURE_PHOTO);
builder.setMediaAction(AnncaConfiguration.MEDIA_ACTION_PHOTO);
builder.setFlashMode(AnncaConfiguration.FLASH_MODE_AUTO);
builder.setMediaQuality(AnncaConfiguration.MEDIA_QUALITY_HIGH);
builder.setMediaResultBehaviour(AnncaConfiguration.PREVIEW);
new Annca(builder.build()).launchCamera();

How can I get the file path through onActivityResult? Apparently the onActivityResult is not even called after clicking the save button (after capturing the photo).

Thanks!

**Comment by memfis19** [comment]
Pls look at: https://stackoverflow.com/a/6147919
