### ISSUE TITLE
camera control design

### ISSUE THREAD

**Issue by shiv71** [memfis19/Annca#6]
I want to modify camera control layout design camera control button position and design. How can i do it.

**Comment by memfis19** [comment]
Hi, you can do it with next steps:

-Extend your activity from **AnncaCameraActivity<T>**, where **T** is type of camera id - its different for camera 1 and camera 2 api, for camera 1 api its **int** value, for camera 2 its **String** value;
-Declare it in the manifest only in **Portrait mode**.
-Override all methods - they are mostly connected with settings for camera controller, if you have some quiestions you can look at **BaseAnncaActivity** in annca module or ask me;
-For method _createCameraController_ use **Camera1Controller** or **Camera2Controller** respectively;
-If you want to rotate your views do it inside _onScreenRotation(int degrees)_ method;
-For setting your camera **control** layout use method _getUserContentView()_ - where you should return your inflated custom control layout;
-If you pass some parameters to your camera via bundle please use method _onProcessBundle(Bundle savedInstanceState)_ which will be called before _getUserContentView(_);
-In case you need to retrieve some data from camera controller or manager use in or after method _onCameraControllerReady()_ was called (i.e. current camera id).
