### ISSUE TITLE
onActiviyResult

### ISSUE THREAD

**Issue by shiv71** [memfis19/Annca#7]
when i call this code by fragment 

AnncaConfiguration.Builder videoLimited = new AnncaConfiguration.Builder(activity, CAPTURE_MEDIA);
               videoLimited.setMediaAction(AnncaConfiguration.MEDIA_ACTION_VIDEO);
               videoLimited.setMediaQuality(AnncaConfiguration.MEDIA_QUALITY_AUTO);
               videoLimited.setVideoFileSize(5 * 1024 * 1024);
               videoLimited.setMinimumVideoDuration(1 * 30 * 1000);
               videoLimited.setVideoDuration(1 * 30 * 1000);

               new Annca(videoLimited.build()).launchCamera();

onActivityResult method not calling in fragment

**Comment by memfis19** [comment]
Hi, thank you for your feedback. Indeed, it's fault in code, will be fixed asap.

**Comment by shiv71** [comment]
if you get any solution regarding this issue than please reply here asap because it is urgent for me 
Thanks

**Comment by memfis19** [comment]
The issue connected with how camera activity launches, now I launch activity next way: ```activity.startActivityFoResult```, so in this case fragment will not receive callback in ```onActivityResult```. I will fix it. But if you really need to fix this issue very fast, you can use next workarounds:
1. **Callback**, add some custom callback to fragment and invoke it in fragment, when activity, which hosts fragment, will receive result in ```onActivityResult```
2. Force invoke ```onActivityResult``` in fragment. You can do it with this code in activity which hosts your fragment:
```
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        List<Fragment> fragments = getSupportFragmentManager().getFragments();
        if (fragments != null) {
            for (Fragment fragment : fragments) {
                if (fragment != null) fragment.onActivityResult(requestCode, resultCode, data);
            }
        }
    }
```
In case you're using support fragments in other case replace ```getSupportFragmentManager``` with ```getFragmentManager```.

**Comment by memfis19** [comment]
Fixed in version 0.3.2. Please look at sample project.

**Comment by shiv71** [comment]
what is new in 0.3.2 version.

**Comment by memfis19** [comment]
Hi, added next features:
-Flash supporting;
-Launching camera from fragments, to receive ```onActivityResult``` within fragment.

**Comment by shiv71** [comment]
hello memfis19 
Flash button not show on video recording page it show only photo capture page
